# Generated by Django 5.2.1 on 2026-01-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_password_reset_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]

