# Generated by Django 5.2.1 on 2026-01-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_add_librarian_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('LIBRARIAN', 'Librarian'), ('WORKING', 'Working')], default='STUDENT', max_length=20),
        ),
    ]
