# Generated by ChatGPT on 2026-01-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_expand_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
