# Generated by ChatGPT on 2026-01-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_add_avatar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
