# Generated by Django 5.2.1 on 2026-03-05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_add_staff_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('BORROW_APPROVED', 'Borrow approved'), ('BORROW_REJECTED', 'Borrow rejected'), ('RETURN_APPROVED', 'Return approved'), ('RETURN_REJECTED', 'Return rejected'), ('RENEWAL_SUCCESS', 'Renewal success'), ('FINE_CREATED', 'Fine created'), ('FINE_PAID', 'Fine paid'), ('FINE_WAIVED', 'Fine waived'), ('RESERVATION_CREATED', 'Reservation created'), ('RESERVATION_AVAILABLE', 'Reservation available'), ('RESERVATION_EXPIRED', 'Reservation expired'), ('RESERVATION_CANCELLED', 'Reservation cancelled'), ('DUE_SOON', 'Due soon')], max_length=40)),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
