# Generated by Django 5.2.1 on 2026-03-15 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_notification_notification_type_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(help_text='Faculty ID allowed to self-register as a teacher account.', max_length=20, unique=True, verbose_name='Faculty ID')),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_teacher_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Approved Teacher',
                'verbose_name_plural': 'Approved Teachers',
                'ordering': ['staff_id'],
            },
        ),
    ]
