# Generated by Django 5.2.1 on 2026-03-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_user_email_verified_loginotpcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(help_text='Official student ID from the enrollment list.', max_length=20, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('school_email', models.EmailField(blank=True, max_length=254)),
                ('program', models.CharField(blank=True, max_length=120)),
                ('year_level', models.CharField(blank=True, max_length=40)),
                ('academic_term', models.CharField(blank=True, max_length=80)),
                ('is_currently_enrolled', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Enrollment record',
                'verbose_name_plural': 'Enrollment records',
                'ordering': ['student_id'],
            },
        ),
    ]
