# Generated by Django 5.2.1 on 2026-03-26 15:55

from django.db.models import Count
import django.db.models.functions.text
from django.db import migrations, models


def normalize_existing_user_emails(apps, schema_editor):
    User = apps.get_model('user', 'User')

    for user in User.objects.exclude(email__isnull=True).only('pk', 'email').iterator():
        normalized = (user.email or '').strip().lower() or None
        if normalized != user.email:
            User.objects.filter(pk=user.pk).update(email=normalized)

    duplicates = (
        User.objects.exclude(email__isnull=True)
        .values('email')
        .annotate(total=Count('id'))
        .filter(total__gt=1)
    )
    if duplicates.exists():
        duplicate_email = duplicates[0]['email']
        raise RuntimeError(
            f"Cannot apply user_email_ci_unique because duplicate email exists after normalization: {duplicate_email}"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0025_alter_notification_notification_type'),
    ]

    operations = [
        migrations.RunPython(normalize_existing_user_emails, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('email__isnull', False)), name='user_email_ci_unique'),
        ),
    ]
