# Generated by Django 5.2.1 on 2026-04-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_user_email_ci_unique'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS user_teacherrecord (
                id bigserial PRIMARY KEY,
                staff_id varchar(20) NOT NULL UNIQUE,
                full_name varchar(100) NOT NULL DEFAULT '',
                school_email varchar(254) NOT NULL DEFAULT '',
                department varchar(120) NOT NULL DEFAULT '',
                academic_term varchar(80) NOT NULL DEFAULT '',
                is_active boolean NOT NULL DEFAULT true,
                notes text NOT NULL DEFAULT '',
                created_at timestamptz NOT NULL,
                updated_at timestamptz NOT NULL
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS user_teacherrecord;",
            state_operations=[
                migrations.CreateModel(
                    name='TeacherRecord',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('staff_id', models.CharField(help_text='Official faculty ID from the approved teacher records.', max_length=20, unique=True, verbose_name='Faculty ID')),
                        ('full_name', models.CharField(blank=True, max_length=100)),
                        ('school_email', models.EmailField(blank=True, max_length=254)),
                        ('department', models.CharField(blank=True, max_length=120)),
                        ('academic_term', models.CharField(blank=True, max_length=80)),
                        ('is_active', models.BooleanField(default=True)),
                        ('notes', models.TextField(blank=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'verbose_name': 'Teacher record',
                        'verbose_name_plural': 'Teacher records',
                        'ordering': ['staff_id'],
                    },
                ),
            ],
        ),
    ]
