# Generated by Django 5.2.1 on 2026-01-16 19:10

from django.db import migrations, models


def populate_usernames(apps, schema_editor):
    User = apps.get_model('user', 'User')

    for user in User.objects.all().order_by('id'):
        if getattr(user, 'username', None):
            continue

        if user.student_id:
            base = user.student_id
        elif user.email:
            base = user.email.split('@')[0] or f"user{user.id}"
        else:
            base = f"user{user.id}"

        candidate = base
        suffix = 1
        while User.objects.filter(username=candidate).exclude(id=user.id).exists():
            candidate = f"{base}{suffix}"
            suffix += 1

        user.username = candidate
        user.save(update_fields=['username'])


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_options_user_student_id_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.RunPython(populate_usernames, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
