# Generated by Django 5.2.1 on 2026-01-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_add_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(
                blank=True,
                help_text='Optional contact phone number',
                max_length=20,
                null=True,
            ),
        ),
    ]

