# Generated by Django 5.2.1 on 2026-01-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_add_email_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordresetcode',
            old_name='phone_number',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
