# Generated by Django 5.2.1 on 2026-01-27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_reset_phone_to_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]

