# Generated by ChatGPT on 2026-01-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('STUDENT', 'Student'),
                    ('LIBRARIAN', 'Librarian'),
                    ('WORKING', 'Working Student'),
                    ('ADMIN', 'Admin'),
                    ('STAFF', 'Staff'),
                ],
                default='STUDENT',
            ),
        ),
    ]
