# Generated by ChatGPT on 2026-02-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_replace_avatar_url_with_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff_id',
            field=models.CharField(
                blank=True,
                help_text='Unique faculty ID number',
                max_length=20,
                null=True,
                unique=True,
                verbose_name='Faculty ID',
            ),
        ),
    ]
