# Generated by Django 5.2.1 on 2026-03-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_passwordresetcode_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('BORROW_APPROVED', 'Borrow approved'), ('BORROW_REJECTED', 'Borrow rejected'), ('RETURN_APPROVED', 'Return approved'), ('RETURN_REJECTED', 'Return rejected'), ('RENEWAL_SUCCESS', 'Renewal success'), ('REPORT_SUBMITTED', 'Report submitted'), ('FINE_CREATED', 'Fine created'), ('FINE_PAID', 'Fine paid'), ('FINE_WAIVED', 'Fine waived'), ('RESERVATION_CREATED', 'Reservation created'), ('RESERVATION_AVAILABLE', 'Reservation available'), ('RESERVATION_EXPIRED', 'Reservation expired'), ('RESERVATION_CANCELLED', 'Reservation cancelled'), ('DUE_SOON', 'Due soon')], max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('LIBRARIAN', 'Librarian'), ('WORKING', 'Working Student'), ('ADMIN', 'Admin'), ('STAFF', 'Staff')], default='STUDENT', max_length=20),
        ),
    ]
