# Generated by Django 5.2.1 on 2026-03-15 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_approvedteacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApprovedTeacher',
        ),
    ]
