"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_env_file() -> None:
    env_path = BASE_DIR / '.env'
    if not env_path.exists():
        return
    for raw_line in env_path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if not key:
            continue
        current_value = os.environ.get(key)
        if current_value is None or current_value == '':
            os.environ[key] = value


load_env_file()


def get_env_list(key: str, default: list[str]) -> list[str]:
    raw = os.getenv(key, "")
    if not raw:
        return default
    return [item.strip() for item in raw.split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-xf1nsfih1-bbqk19@+3l+97bsh7g!6+@yzij@_r0qq3apnjb06')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = get_env_list(
    "DJANGO_ALLOWED_HOSTS",
    ["localhost", "127.0.0.1", "0.0.0.0", "10.0.2.2"],
)
if DEBUG and "*" not in ALLOWED_HOSTS:
    # Development convenience for mobile devices on LAN/tunnel hosts.
    ALLOWED_HOSTS.append("*")


# Application definition
INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',

    'user.apps.UserConfig',
    'books.apps.BooksConfig',

    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django.contrib.staticfiles',
]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': ( 
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}
MAX_ACTIVE_BORROWS = 3
BORROW_DURATION_DAYS = 4
RENEWAL_DURATION_DAYS = 4
MAX_RENEWALS_PER_BORROW = 2
LATE_FEE_PER_DAY = os.getenv('LATE_FEE_PER_DAY', '100.00')
DUE_SOON_REMINDER_DAYS = 1
AUTO_RUN_BORROW_AUTOMATION_DAILY = True
MAX_UNPAID_FINE_AMOUNT = 50.00
RESERVATION_NOTIFICATION_HOURS = 24
JAZZMIN_SETTINGS = {
    "site_title": "Salazar Library System",
    "site_header": "Salazar Library System",
    "site_brand": "Salazar Library System",
    "welcome_sign": "Welcome, Librarian",
    "theme": "flatly",
    "show_sidebar": True,
    "navigation_expanded": True,
    "search_model": ["books.Book", "books.BookCopy", "user.User"],
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index"},
        {"app": "books"},
        {"app": "user"},
    ],
    "custom_links": {
        "books": [
            {
                "name": "Overdue books",
                "url": "/admin/books/borrowedbook/?overdue_status=overdue",
                "icon": "fas fa-exclamation-circle",
                "permissions": ["books.view_borrowedbook"],
            },
        ],
    },
    "icons": {
        "books": "fas fa-book",
        "books.book": "fas fa-book",
        "books.bookcopy": "fas fa-barcode",
        "books.borrowrequest": "fas fa-hand-holding",
        "books.borrowedbook": "fas fa-book-reader",
        "books.returnrequest": "fas fa-undo",
        "books.category": "fas fa-tags",
        "user": "fas fa-user-graduate",
        "user.user": "fas fa-user-graduate",
        "auth": "fas fa-users-cog",
        "auth.group": "fas fa-users",
    },
    "related_modal_active": True,
    "custom_css": "admin/custom.css",
}
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": True,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "theme": "flatly",
    "dark_mode_theme": "darkly",
}
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Password reset via phone (dev-friendly defaults)
PASSWORD_RESET_CODE_TTL_MINUTES = 10
PASSWORD_RESET_CODE_LENGTH = 6
PASSWORD_RESET_MAX_ATTEMPTS = 5
PASSWORD_RESET_DEBUG_RETURN_CODE = os.getenv(
    'PASSWORD_RESET_DEBUG_RETURN_CODE',
    'true' if DEBUG else 'false',
).lower() in ('1', 'true', 'yes')

# Email verification for registration
EMAIL_VERIFICATION_CODE_TTL_MINUTES = 15
EMAIL_VERIFICATION_CODE_LENGTH = 6
EMAIL_VERIFICATION_MAX_ATTEMPTS = 5

# Login OTP for email verification
LOGIN_OTP_CODE_TTL_MINUTES = 15
LOGIN_OTP_CODE_LENGTH = 6
LOGIN_OTP_MAX_ATTEMPTS = 5

# Email configuration for password resets
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'true').lower() in ('1', 'true', 'yes')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'no-reply@salazar-library.local')
PASSWORD_RESET_WEB_URL = os.getenv(
    'PASSWORD_RESET_WEB_URL',
    'http://localhost:3000/forgot-password',
)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'books.middleware.DailyBorrowAutomationMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Only allow all origins in development
CORS_ALLOWED_ORIGINS = get_env_list(
    "CORS_ALLOWED_ORIGINS",
    ["http://localhost:3000", "http://127.0.0.1:3000"],
)
ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# Database - Use environment variables for production
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'library'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'postgre'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

AUTH_USER_MODEL = 'user.User'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'user.password_validators.PasswordCompositionValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
