# Generated by Django 5.2.1 on 2026-01-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_back',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
    ]
