# Generated by Django 5.2.1 on 2026-01-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_borrowrequest_receipt_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned')], default='PENDING', max_length=20),
        ),
    ]
