# Generated by Django 5.2.1 on 2026-01-18 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_alter_borrowrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowedBook',
            fields=[],
            options={
                'verbose_name': 'Borrowed book',
                'verbose_name_plural': 'Borrowed books',
                'proxy': True,
            },
            bases=('books.borrowrequest',),
        ),
    ]
