# Generated by Django 5.2.1 on 2026-01-18 03:35

from datetime import timedelta

from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def backfill_due_dates(apps, schema_editor):
    BorrowRequest = apps.get_model('books', 'BorrowRequest')
    borrow_days = getattr(settings, 'BORROW_DURATION_DAYS', 14)
    queryset = BorrowRequest.objects.filter(
        due_date__isnull=True,
        status__in=['APPROVED', 'RETURNED'],
    )
    for borrow_request in queryset.iterator():
        base_dt = borrow_request.processed_at or borrow_request.requested_at or timezone.now()
        due_date = base_dt.date() + timedelta(days=borrow_days)
        BorrowRequest.objects.filter(pk=borrow_request.pk).update(due_date=due_date)


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_borrowed_book_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_due_dates, migrations.RunPython.noop),
    ]
