# Generated by Django 5.2.1 on 2026-01-25 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_borrowrequest_due_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HoldRequest',
        ),
    ]
