# Generated by Django 5.2.1 on 2026-03-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_borrowrequest_last_renewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='requested_borrow_days',
            field=models.PositiveIntegerField(default=14),
        ),
    ]
