# Generated by Django 5.2.1 on 2026-03-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_borrowrequest_requested_borrow_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='location_shelf',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
