# Generated by Django 5.2.1 on 2026-03-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0022_bookreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='last_reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='next_report_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='reporting_frequency',
            field=models.CharField(choices=[('NONE', 'No reporting'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='NONE', max_length=10),
        ),
    ]
