"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path
from datetime import timedelta

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_env_file() -> None:
    env_path = BASE_DIR / '.env'
    if not env_path.exists():
        return
    for raw_line in env_path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if not key:
            continue
        current_value = os.environ.get(key)
        if current_value is None or current_value == '':
            os.environ[key] = value


load_env_file()


def get_env_list(key: str, default: list[str]) -> list[str]:
    raw = os.getenv(key, "")
    if not raw:
        return default
    return [item.strip() for item in raw.split(",") if item.strip()]


def get_env_str(key: str, default: str = "") -> str:
    raw = os.getenv(key)
    if raw is None:
        return default
    return raw.strip()


def get_env_bool(key: str, default: bool) -> bool:
    raw = os.getenv(key)
    if raw is None:
        return default
    return raw.strip().lower() in ('1', 'true', 'yes', 'on')


def get_env_int(key: str, default: int) -> int:
    raw = os.getenv(key)
    if raw is None or raw.strip() == "":
        return default
    try:
        return int(raw)
    except ValueError:
        return default


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_env_bool('DEBUG', True)
RUNNING_TESTS = 'test' in sys.argv
ENABLE_PRODUCTION_SECURITY = not (DEBUG or RUNNING_TESTS)
DEFAULT_WEB_URL = 'http://localhost:3000'
DEFAULT_ALLOWED_HOSTS = ["localhost", "127.0.0.1", "0.0.0.0", "10.0.2.2"]
DEFAULT_CORS_ALLOWED_ORIGINS = ["http://localhost:3000", "http://127.0.0.1:3000"]


def require_production_env(key: str) -> str:
    value = get_env_str(key)
    if value:
        return value
    raise ImproperlyConfigured(f'{key} must be set when DEBUG is False.')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG or RUNNING_TESTS:
        SECRET_KEY = 'dev-only-salazar-library-secret-key-7Q!m2#Xr8@Lk4$Vp9%Ns6^Ta1&Hg3*'
    else:
        raise ImproperlyConfigured('SECRET_KEY must be set when DEBUG is False.')

ALLOWED_HOSTS = get_env_list(
    "DJANGO_ALLOWED_HOSTS",
    DEFAULT_ALLOWED_HOSTS,
)
if ENABLE_PRODUCTION_SECURITY and not get_env_str('DJANGO_ALLOWED_HOSTS'):
    raise ImproperlyConfigured('DJANGO_ALLOWED_HOSTS must be set when DEBUG is False.')
if DEBUG and "*" not in ALLOWED_HOSTS:
    # Development convenience for mobile devices on LAN/tunnel hosts.
    ALLOWED_HOSTS.append("*")


# Application definition
INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',

    'user.apps.UserConfig',
    'books.apps.BooksConfig',

    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django.contrib.staticfiles',
]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.ScopedRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'login': '10/minute',
        'register': '10/hour',
        'otp_send': '5/hour',
        'otp_verify': '10/hour',
        'update_email': '10/hour',
        'password_reset_request': '5/hour',
        'password_reset_verify': '10/hour',
        'password_reset_confirm': '10/hour',
        'email_verification_send': '5/hour',
        'email_verification_verify': '10/hour',
        'contact': '20/hour',
    },
}
LOGIN_FAILURE_LIMIT = get_env_int('LOGIN_FAILURE_LIMIT', 5)
LOGIN_FAILURE_WINDOW_MINUTES = get_env_int('LOGIN_FAILURE_WINDOW_MINUTES', 15)
LOGIN_LOCKOUT_MINUTES = get_env_int('LOGIN_LOCKOUT_MINUTES', 15)
MAX_ACTIVE_BORROWS = 3
BORROW_DURATION_DAYS = 4
RENEWAL_DURATION_DAYS = 4
MAX_RENEWALS_PER_BORROW = 2
LATE_FEE_PER_DAY = os.getenv('LATE_FEE_PER_DAY', '100.00')
DUE_SOON_REMINDER_DAYS = 1
AUTO_RUN_BORROW_AUTOMATION_DAILY = True
MAX_UNPAID_FINE_AMOUNT = 50.00
RESERVATION_NOTIFICATION_HOURS = 24
JAZZMIN_SETTINGS = {
    "site_title": "Salazar Library System",
    "site_header": "Salazar Library System",
    "site_brand": "Salazar Library System",
    "welcome_sign": "Welcome, Librarian",
    "theme": "flatly",
    "show_sidebar": True,
    "navigation_expanded": True,
    "search_model": ["books.Book", "books.BookCopy", "user.User"],
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index"},
        {"app": "books"},
        {"app": "user"},
    ],
    "custom_links": {
        "books": [
            {
                "name": "Overdue books",
                "url": "/admin/books/borrowedbook/?overdue_status=overdue",
                "icon": "fas fa-exclamation-circle",
                "permissions": ["books.view_borrowedbook"],
            },
        ],
    },
    "icons": {
        "books": "fas fa-book",
        "books.book": "fas fa-book",
        "books.bookcopy": "fas fa-barcode",
        "books.borrowrequest": "fas fa-hand-holding",
        "books.borrowedbook": "fas fa-book-reader",
        "books.returnrequest": "fas fa-undo",
        "books.category": "fas fa-tags",
        "user": "fas fa-user-graduate",
        "user.user": "fas fa-user-graduate",
        "auth": "fas fa-users-cog",
        "auth.group": "fas fa-users",
    },
    "related_modal_active": True,
    "custom_css": "admin/custom.css",
}
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": True,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "theme": "flatly",
    "dark_mode_theme": "darkly",
}
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
}

# Short-lived challenge used by OTP and pending-email recovery flows
OTP_CHALLENGE_TTL_MINUTES = get_env_int('OTP_CHALLENGE_TTL_MINUTES', 30)

# Password reset settings
PASSWORD_RESET_CODE_TTL_MINUTES = 10
PASSWORD_RESET_CODE_LENGTH = 6
PASSWORD_RESET_MAX_ATTEMPTS = 5
PASSWORD_RESET_DEBUG_RETURN_CODE = get_env_bool('PASSWORD_RESET_DEBUG_RETURN_CODE', False)

# Email verification for registration
EMAIL_VERIFICATION_CODE_TTL_MINUTES = 15
EMAIL_VERIFICATION_CODE_LENGTH = 6
EMAIL_VERIFICATION_MAX_ATTEMPTS = 5

# Login OTP for email verification
LOGIN_OTP_CODE_TTL_MINUTES = 15
LOGIN_OTP_CODE_LENGTH = 6
LOGIN_OTP_MAX_ATTEMPTS = 5

# Email configuration for password resets
EMAIL_BACKEND = get_env_str('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = get_env_str('EMAIL_HOST')
EMAIL_PORT = int(get_env_str('EMAIL_PORT', '587'))
EMAIL_USE_TLS = get_env_bool('EMAIL_USE_TLS', True)
EMAIL_HOST_USER = get_env_str('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = get_env_str('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = get_env_str('DEFAULT_FROM_EMAIL', 'no-reply@salazar-library.local')
LIBRARY_WEB_URL = get_env_str('LIBRARY_WEB_URL', DEFAULT_WEB_URL)
if ENABLE_PRODUCTION_SECURITY and LIBRARY_WEB_URL == DEFAULT_WEB_URL:
    raise ImproperlyConfigured('LIBRARY_WEB_URL must be set when DEBUG is False.')
PASSWORD_RESET_WEB_URL = get_env_str(
    'PASSWORD_RESET_WEB_URL',
    f"{LIBRARY_WEB_URL.rstrip('/')}/forgot-password",
)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'books.middleware.DailyBorrowAutomationMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Only allow all origins in development
CORS_ALLOWED_ORIGINS = get_env_list(
    "CORS_ALLOWED_ORIGINS",
    DEFAULT_CORS_ALLOWED_ORIGINS,
)
CORS_ALLOWED_ORIGIN_REGEXES = get_env_list(
    "CORS_ALLOWED_ORIGIN_REGEXES",
    [],
)
if ENABLE_PRODUCTION_SECURITY and not (
    get_env_str('CORS_ALLOWED_ORIGINS') or get_env_str('CORS_ALLOWED_ORIGIN_REGEXES')
):
    raise ImproperlyConfigured(
        'Either CORS_ALLOWED_ORIGINS or CORS_ALLOWED_ORIGIN_REGEXES must be set when DEBUG is False.'
    )
csrf_default_origins = CORS_ALLOWED_ORIGINS.copy() if get_env_str("CORS_ALLOWED_ORIGINS") else []
CSRF_TRUSTED_ORIGINS = get_env_list("CSRF_TRUSTED_ORIGINS", csrf_default_origins)
SECURE_SSL_REDIRECT = get_env_bool('SECURE_SSL_REDIRECT', ENABLE_PRODUCTION_SECURITY)
SESSION_COOKIE_SECURE = get_env_bool('SESSION_COOKIE_SECURE', ENABLE_PRODUCTION_SECURITY)
CSRF_COOKIE_SECURE = get_env_bool('CSRF_COOKIE_SECURE', ENABLE_PRODUCTION_SECURITY)
SECURE_HSTS_SECONDS = get_env_int('SECURE_HSTS_SECONDS', 0 if not ENABLE_PRODUCTION_SECURITY else 31536000)
SECURE_HSTS_INCLUDE_SUBDOMAINS = get_env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', ENABLE_PRODUCTION_SECURITY)
SECURE_HSTS_PRELOAD = get_env_bool('SECURE_HSTS_PRELOAD', ENABLE_PRODUCTION_SECURITY)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = os.getenv('SECURE_REFERRER_POLICY', 'same-origin')
SECURE_CROSS_ORIGIN_OPENER_POLICY = os.getenv('SECURE_CROSS_ORIGIN_OPENER_POLICY', 'same-origin')
X_FRAME_OPTIONS = os.getenv('X_FRAME_OPTIONS', 'DENY')
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = os.getenv('SESSION_COOKIE_SAMESITE', 'Lax')
CSRF_COOKIE_SAMESITE = os.getenv('CSRF_COOKIE_SAMESITE', 'Lax')
if get_env_bool('USE_X_FORWARDED_PROTO', ENABLE_PRODUCTION_SECURITY):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# Database - Use environment variables for production
DB_NAME = get_env_str('DB_NAME', 'library')
DB_USER = get_env_str('DB_USER', 'postgres')
DB_PASSWORD = get_env_str('DB_PASSWORD', 'postgre')
DB_HOST = get_env_str('DB_HOST', 'localhost')
DB_PORT = get_env_str('DB_PORT', '5432')
if ENABLE_PRODUCTION_SECURITY:
    for env_key in ('DB_NAME', 'DB_USER', 'DB_PASSWORD', 'DB_HOST', 'DB_PORT'):
        require_production_env(env_key)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': DB_NAME,
        'USER': DB_USER,
        'PASSWORD': DB_PASSWORD,
        'HOST': DB_HOST,
        'PORT': DB_PORT,
        'CONN_MAX_AGE': get_env_int('DB_CONN_MAX_AGE', 60 if ENABLE_PRODUCTION_SECURITY else 0),
        'CONN_HEALTH_CHECKS': get_env_bool('DB_CONN_HEALTH_CHECKS', ENABLE_PRODUCTION_SECURITY),
    }
}
DB_SSLMODE = get_env_str('DB_SSLMODE')
if DB_SSLMODE:
    DATABASES['default']['OPTIONS'] = {
        'sslmode': DB_SSLMODE,
    }


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

AUTH_USER_MODEL = 'user.User'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'user.password_validators.PasswordCompositionValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = get_env_str('STATIC_URL', '/static/')
STATIC_ROOT = Path(get_env_str('STATIC_ROOT', str(BASE_DIR / 'staticfiles')))
MEDIA_URL = get_env_str('MEDIA_URL', '/media/')
MEDIA_ROOT = Path(get_env_str('MEDIA_ROOT', str(BASE_DIR / 'media')))
SERVE_MEDIA_FILES = get_env_bool('SERVE_MEDIA_FILES', DEBUG)
if ENABLE_PRODUCTION_SECURITY and not get_env_str('MEDIA_ROOT'):
    raise ImproperlyConfigured(
        'MEDIA_ROOT must be set when DEBUG is False. Use a persistent path such as a mounted volume.'
    )
MEDIA_ROOT.mkdir(parents=True, exist_ok=True)
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': (
            'whitenoise.storage.CompressedManifestStaticFilesStorage'
            if ENABLE_PRODUCTION_SECURITY
            else 'django.contrib.staticfiles.storage.StaticFilesStorage'
        ),
    },
}
WHITENOISE_AUTOREFRESH = DEBUG
WHITENOISE_USE_FINDERS = DEBUG
LOG_LEVEL = get_env_str('LOG_LEVEL', 'INFO' if ENABLE_PRODUCTION_SECURITY else 'DEBUG').upper()
# Keep framework logs quieter in development unless explicitly overridden.
DJANGO_LOG_LEVEL = get_env_str('DJANGO_LOG_LEVEL', 'INFO').upper()
DJANGO_AUTORELOAD_LOG_LEVEL = get_env_str('DJANGO_AUTORELOAD_LOG_LEVEL', 'INFO').upper()
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(asctime)s %(levelname)s %(name)s %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': LOG_LEVEL,
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': DJANGO_LOG_LEVEL,
            'propagate': False,
        },
        'django.utils.autoreload': {
            'handlers': ['console'],
            'level': DJANGO_AUTORELOAD_LOG_LEVEL,
            'propagate': False,
        },
        'books': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'user': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
