# Generated by Django 5.2.1 on 2026-01-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='copies_available',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
