# Generated by Django 5.2.1 on 2026-01-16 03:45

from django.db import migrations, models


def seed_categories(apps, schema_editor):
    Book = apps.get_model('books', 'Book')
    Category = apps.get_model('books', 'Category')

    for book in Book.objects.exclude(genre__isnull=True).exclude(genre=''):
        name = book.genre.strip()
        if not name:
            continue
        category, _ = Category.objects.get_or_create(name=name)
        book.categories.add(category)


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_remove_bookloan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='books', to='books.category'),
        ),
        migrations.RunPython(seed_categories, migrations.RunPython.noop),
    ]
