# Generated by Django 5.2.1 on 2026-01-16 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_book_copies(apps, schema_editor):
    Book = apps.get_model('books', 'Book')
    BookCopy = apps.get_model('books', 'BookCopy')

    for book in Book.objects.all():
        total = book.copies_available or 0
        if total < 0:
            total = 0
        for index in range(total):
            BookCopy.objects.create(
                book=book,
                barcode=f"{book.isbn}-{index + 1:04d}",
                status='AVAILABLE',
                location_room='',
                location_shelf='',
                is_reference_only=False,
            )
        Book.objects.filter(pk=book.pk).update(available=total > 0)


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_return_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='grade_level',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='copies_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BORROWED', 'Borrowed'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=20)),
                ('location_room', models.CharField(blank=True, default='', max_length=100)),
                ('location_shelf', models.CharField(blank=True, default='', max_length=100)),
                ('is_reference_only', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='books.book')),
            ],
            options={
                'ordering': ['barcode', 'id'],
            },
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='copy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow_requests', to='books.bookcopy'),
        ),
        migrations.CreateModel(
            name='HoldRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FULFILLED', 'Fulfilled'), ('CANCELED', 'Canceled')], default='ACTIVE', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hold_requests', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hold_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['requested_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='holdrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('user', 'book'), name='unique_active_hold_request'),
        ),
        migrations.RunPython(create_book_copies, migrations.RunPython.noop),
    ]
