# Generated by Django 5.2.1 on 2026-01-17 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_hold_statuses(apps, schema_editor):
    HoldRequest = apps.get_model('books', 'HoldRequest')
    HoldRequest.objects.filter(status='ACTIVE').update(status='APPROVED')


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_title_copy_hold'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            
            model_name='holdrequest',
            name='unique_active_hold_request',
        ),
        migrations.AddField(
            model_name='holdrequest',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holdrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_hold_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='holdrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('FULFILLED', 'Fulfilled'), ('REJECTED', 'Rejected'), ('CANCELED', 'Canceled')], default='PENDING', max_length=20),
        ),
        migrations.RunPython(migrate_hold_statuses, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='holdrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'APPROVED'])), fields=('user', 'book'), name='unique_open_hold_request'),
        ),
    ]
