# Generated by Django 5.2.1 on 2026-02-27 00:00

import decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_remove_hold_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='due_soon_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='late_fee_amount',
            field=models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=10),
        ),
    ]
